name: Package for Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  package-unity-2019-4:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2019.4.40f1-base-1.0.1
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Package
      run: |
        chmod a+x scripts/ci/activate-license.sh
        ./scripts/ci/activate-license.sh
        echo "Activation done. Packaging..."
        python scripts/ExportUnityPackage.py /opt/unity/Editor/Unity -nodisplay
      shell: bash
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_BASE64 }}
    - uses: actions/upload-artifact@v3
      with:
        name: UnityVolumeRendering-2019.unitypackage
        path: UnityVolumeRendering.unitypackage
  package-unity-2021-3:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2021.3.9f1-base-1.0.1
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Package
      run: |
        chmod a+x scripts/ci/activate-license.sh
        ./scripts/ci/activate-license.sh
        echo "Activation done. Packaging..."
        python scripts/ExportUnityPackage.py /opt/unity/Editor/Unity -nodisplay
      shell: bash
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_BASE64 }}
    - uses: actions/upload-artifact@v3
      with:
        name: UnityVolumeRendering-2020.3+.unitypackage
        path: UnityVolumeRendering.unitypackage
